from __future__ import annotations

from app.modules.shared.constants import (
    ASSISTANT_GMAIL_PROVIDER,
    GOOGLE_CALENDAR_PROVIDER,
    GOOGLE_CALENDAR_SOURCE,
    GOOGLE_OAUTH_PROVIDERS,
    GOOGLE_WORKSPACE_PROVIDER,
    TEST_CLIENT_EMAIL,
    TEST_CLIENT_GMAIL_PROVIDER,
    TEST_CLIENT_NAME,
)

__all__ = [
    "ASSISTANT_GMAIL_PROVIDER",
    "GOOGLE_CALENDAR_PROVIDER",
    "GOOGLE_CALENDAR_SOURCE",
    "GOOGLE_OAUTH_PROVIDERS",
    "GOOGLE_WORKSPACE_PROVIDER",
    "TEST_CLIENT_EMAIL",
    "TEST_CLIENT_GMAIL_PROVIDER",
    "TEST_CLIENT_NAME",
]
